disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Pierre Mesure | Tech for democracy"

[params]
  displayName = "🇬🇧 English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Tech for democracy"
  copyright = "CC-BY 4.0 Pierre Mesure"

[params.author]
  name = "Pierre Mesure"
  image = "img/me.webp"
  imageQuality = 90
  headline = "Digital activist working to improve democracy through openness, participation and innovation"
  bio = "Digital activist working to improve democracy through openness, participation and innovation"
  links = [
    { email = "mailto:pierre@mesu.re" },
    { linkedin = "https://linkedin.com/in/pierremesure" },
    { github = "https://github.com/pierremesure" },
    { huggingface = "https://huggingface.com/pierremesure" },
    { medium = "https://medium.com/pierremesure" },
  ]
